require('dotenv').config({ path: require('path').join(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Lesson = require('../models/Lesson');
const Student = require('../models/Student');

const lessons = [
  {
    dayNumber: 1, topic: 'Simple Present Tense', difficulty: 'easy', timeLimit: 1800,
    explanation: 'The Simple Present Tense is used to describe habits, general truths, and fixed schedules.',
    rules: ['Use base form of verb for I/You/We/They', 'Add -s/-es for He/She/It', 'Use "do" or "does" for questions/negatives'],
    examples: ['She plays cricket every day.', 'They go to school.', 'He does not eat meat.'],
    commonMistakes: ['Adding -s for plural subjects', 'Forgetting -s for He/She/It', 'Using "is" instead of "does"'],
    questions: [
      { type: 'mcq', question: 'She ___ to school every day.', options: ['go','goes','going','went'], correctAnswer: 'goes', explanation: 'Third person singular takes -es' },
      { type: 'mcq', question: 'They ___ football on weekends.', options: ['plays','play','played','playing'], correctAnswer: 'play', explanation: 'Plural subject uses base form' },
      { type: 'fill', question: 'He ___ (read) a book daily.', correctAnswer: 'reads' },
      { type: 'fill', question: 'We ___ (not/eat) junk food.', correctAnswer: 'do not eat' },
      { type: 'mcq', question: 'Does she ___ English?', options: ['speaks','speak','spoken','speaking'], correctAnswer: 'speak', explanation: 'After "does", use base form' },
      { type: 'error', question: 'They goes to market every Sunday.', correctAnswer: 'They go to market every Sunday.' },
      { type: 'transform', question: 'She reads books. (Negative)', correctAnswer: 'She does not read books.' },
      { type: 'mcq', question: 'The sun ___ in the east.', options: ['risen','rise','rises','rose'], correctAnswer: 'rises', explanation: 'General truth, third person singular' },
      { type: 'fill', question: 'My father ___ (work) in a bank.', correctAnswer: 'works' },
      { type: 'transform', question: 'He plays guitar. (Question)', correctAnswer: 'Does he play guitar?' },
    ]
  },
  {
    dayNumber: 2, topic: 'Simple Past Tense', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Simple Past Tense describes completed actions in the past.',
    rules: ['Use V2 (past form) for all subjects', 'Use "did not" for negatives', 'Use "did" for questions'],
    examples: ['She played cricket yesterday.', 'They went to school.', 'He did not eat meat.'],
    commonMistakes: ['Using V1 after "did"', 'Forgetting irregular past forms', 'Using "was" instead of "did"'],
    questions: [
      { type: 'mcq', question: 'She ___ to market yesterday.', options: ['go','goes','went','going'], correctAnswer: 'went' },
      { type: 'fill', question: 'He ___ (write) a letter last night.', correctAnswer: 'wrote' },
      { type: 'mcq', question: 'Did they ___ the match?', options: ['won','win','wins','winning'], correctAnswer: 'win' },
      { type: 'error', question: 'She did not went to school.', correctAnswer: 'She did not go to school.' },
      { type: 'transform', question: 'He ate dinner. (Negative)', correctAnswer: 'He did not eat dinner.' },
      { type: 'fill', question: 'We ___ (see) a movie last week.', correctAnswer: 'saw' },
      { type: 'mcq', question: 'They ___ cricket for two hours.', options: ['play','plays','played','playing'], correctAnswer: 'played' },
      { type: 'transform', question: 'She cooked food. (Question)', correctAnswer: 'Did she cook food?' },
      { type: 'error', question: 'He writed a poem yesterday.', correctAnswer: 'He wrote a poem yesterday.' },
      { type: 'fill', question: 'The teacher ___ (teach) well yesterday.', correctAnswer: 'taught' },
    ]
  },
  {
    dayNumber: 3, topic: 'Simple Future Tense', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Simple Future Tense describes actions that will happen in the future.',
    rules: ['Use will + base verb for all subjects', 'Use will not (won\'t) for negatives', 'Use Will...? for questions'],
    examples: ['She will go to school.', 'They will play football.', 'He will not eat meat.'],
    commonMistakes: ['Using "will" + past form', 'Confusing shall/will', 'Forgetting base form after will'],
    questions: [
      { type: 'mcq', question: 'She ___ visit her grandmother tomorrow.', options: ['will','would','is','was'], correctAnswer: 'will' },
      { type: 'fill', question: 'He ___ (complete) the project by Friday.', correctAnswer: 'will complete' },
      { type: 'mcq', question: 'Will they ___ the match?', options: ['wins','won','win','winning'], correctAnswer: 'win' },
      { type: 'error', question: 'She will went to the market.', correctAnswer: 'She will go to the market.' },
      { type: 'transform', question: 'He will study tonight. (Negative)', correctAnswer: 'He will not study tonight.' },
      { type: 'fill', question: 'We ___ (travel) to Delhi next month.', correctAnswer: 'will travel' },
      { type: 'transform', question: 'They will play. (Question)', correctAnswer: 'Will they play?' },
      { type: 'mcq', question: 'I ___ help you with your homework.', options: ['am','was','will','have'], correctAnswer: 'will' },
      { type: 'error', question: 'He will studied hard.', correctAnswer: 'He will study hard.' },
      { type: 'fill', question: 'The train ___ (arrive) at 6 PM.', correctAnswer: 'will arrive' },
    ]
  },
  {
    dayNumber: 4, topic: 'Present Continuous Tense', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Present Continuous describes actions happening right now or planned future events.',
    rules: ['Use am/is/are + verb-ing', 'Is for He/She/It, Are for You/We/They, Am for I'],
    examples: ['She is playing cricket.', 'They are going to school.', 'I am reading a book.'],
    commonMistakes: ['Forgetting to add -ing', 'Wrong auxiliary (is/are/am)', 'Using with state verbs (like/know)'],
    questions: [
      { type: 'mcq', question: 'She ___ playing in the garden now.', options: ['am','is','are','were'], correctAnswer: 'is' },
      { type: 'fill', question: 'They ___ (study) for exams right now.', correctAnswer: 'are studying' },
      { type: 'mcq', question: 'I ___ cooking dinner at the moment.', options: ['am','is','are','was'], correctAnswer: 'am' },
      { type: 'error', question: 'He are eating lunch now.', correctAnswer: 'He is eating lunch now.' },
      { type: 'transform', question: 'She is reading. (Negative)', correctAnswer: 'She is not reading.' },
      { type: 'fill', question: 'The children ___ (play) outside.', correctAnswer: 'are playing' },
      { type: 'transform', question: 'They are watching TV. (Question)', correctAnswer: 'Are they watching TV?' },
      { type: 'mcq', question: 'We ___ planning a trip next week.', options: ['am','is','are','were'], correctAnswer: 'are' },
      { type: 'error', question: 'I is writing a letter.', correctAnswer: 'I am writing a letter.' },
      { type: 'fill', question: 'He ___ (run) in the park right now.', correctAnswer: 'is running' },
    ]
  },
  {
    dayNumber: 5, topic: 'Past Continuous Tense', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Past Continuous describes an ongoing action at a specific time in the past.',
    rules: ['Use was/were + verb-ing', 'Was for I/He/She/It, Were for You/We/They'],
    examples: ['She was playing when I called.', 'They were studying at 8 PM.'],
    commonMistakes: ['Mixing was/were', 'Forgetting -ing'],
    questions: [
      { type: 'mcq', question: 'She ___ singing when the bell rang.', options: ['is','was','are','were'], correctAnswer: 'was' },
      { type: 'fill', question: 'They ___ (play) football at 5 PM.', correctAnswer: 'were playing' },
      { type: 'mcq', question: 'We ___ watching TV when he arrived.', options: ['was','is','were','are'], correctAnswer: 'were' },
      { type: 'error', question: 'He were sleeping when I called.', correctAnswer: 'He was sleeping when I called.' },
      { type: 'transform', question: 'She was cooking. (Negative)', correctAnswer: 'She was not cooking.' },
      { type: 'fill', question: 'I ___ (read) a novel last night.', correctAnswer: 'was reading' },
      { type: 'transform', question: 'They were playing. (Question)', correctAnswer: 'Were they playing?' },
      { type: 'mcq', question: 'The children ___ making noise all day.', options: ['was','is','were','are'], correctAnswer: 'were' },
      { type: 'error', question: 'She was not slept well last night.', correctAnswer: 'She was not sleeping well last night.' },
      { type: 'fill', question: 'He ___ (write) when the lights went off.', correctAnswer: 'was writing' },
    ]
  },
  {
    dayNumber: 6, topic: 'Present Perfect Tense', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Present Perfect connects past actions to the present.',
    rules: ['Use have/has + past participle (V3)', 'Has for He/She/It, Have for I/You/We/They'],
    examples: ['She has eaten dinner.', 'I have finished my work.', 'They have not arrived yet.'],
    commonMistakes: ['Using V2 instead of V3', 'Wrong auxiliary (has/have)'],
    questions: [
      { type: 'mcq', question: 'She ___ finished her homework.', options: ['have','has','had','is'], correctAnswer: 'has' },
      { type: 'fill', question: 'I ___ (visit) Paris twice.', correctAnswer: 'have visited' },
      { type: 'mcq', question: 'They ___ not completed the project yet.', options: ['has','have','had','is'], correctAnswer: 'have' },
      { type: 'error', question: 'He has went to the market.', correctAnswer: 'He has gone to the market.' },
      { type: 'transform', question: 'She has written a letter. (Negative)', correctAnswer: 'She has not written a letter.' },
      { type: 'fill', question: 'We ___ (eat) at this restaurant before.', correctAnswer: 'have eaten' },
      { type: 'transform', question: 'He has seen the movie. (Question)', correctAnswer: 'Has he seen the movie?' },
      { type: 'mcq', question: 'The teacher ___ just announced the results.', options: ['have','has','had','did'], correctAnswer: 'has' },
      { type: 'error', question: 'They have already leave.', correctAnswer: 'They have already left.' },
      { type: 'fill', question: 'She ___ (lose) her keys.', correctAnswer: 'has lost' },
    ]
  },
  {
    dayNumber: 7, topic: 'Past Perfect Tense', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Past Perfect shows an action completed before another past action.',
    rules: ['Use had + V3 for all subjects', 'Often used with "before", "after", "when", "by the time"'],
    examples: ['She had eaten before he arrived.', 'By 8 PM, they had finished the work.'],
    commonMistakes: ['Confusing with Simple Past', 'Wrong V3 forms'],
    questions: [
      { type: 'mcq', question: 'She ___ already left when I arrived.', options: ['has','have','had','is'], correctAnswer: 'had' },
      { type: 'fill', question: 'By the time we reached, the show ___ (start).', correctAnswer: 'had started' },
      { type: 'mcq', question: 'They ___ not eaten before the party began.', options: ['has','have','had','did'], correctAnswer: 'had' },
      { type: 'error', question: 'He had went home before sunset.', correctAnswer: 'He had gone home before sunset.' },
      { type: 'transform', question: 'She had cooked food. (Negative)', correctAnswer: 'She had not cooked food.' },
      { type: 'fill', question: 'I ___ (finish) my work before he came.', correctAnswer: 'had finished' },
      { type: 'transform', question: 'They had left. (Question)', correctAnswer: 'Had they left?' },
      { type: 'mcq', question: 'After she ___ the letter, she posted it.', options: ['write','writes','has written','had written'], correctAnswer: 'had written' },
      { type: 'error', question: 'We had saw the movie before.', correctAnswer: 'We had seen the movie before.' },
      { type: 'fill', question: 'He ___ (complete) the task by Monday.', correctAnswer: 'had completed' },
    ]
  },
  {
    dayNumber: 8, topic: 'Future Perfect Tense', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Future Perfect expresses an action that will be completed before a specific future time.',
    rules: ['Use will have + V3', 'Often used with "by", "before", "by the time"'],
    examples: ['She will have completed the project by Friday.', 'By 6 PM, they will have arrived.'],
    commonMistakes: ['Omitting "have"', 'Using wrong verb form after will have'],
    questions: [
      { type: 'mcq', question: 'By next year, she ___ graduated.', options: ['will have','has','would','will'], correctAnswer: 'will have' },
      { type: 'fill', question: 'By tonight, I ___ (finish) the report.', correctAnswer: 'will have finished' },
      { type: 'mcq', question: 'They ___ completed the race before noon.', options: ['will has','will have','would have','shall'], correctAnswer: 'will have' },
      { type: 'error', question: 'She will has eaten by then.', correctAnswer: 'She will have eaten by then.' },
      { type: 'transform', question: 'He will have left by 8. (Negative)', correctAnswer: 'He will not have left by 8.' },
      { type: 'fill', question: 'By the time you arrive, we ___ (leave).', correctAnswer: 'will have left' },
      { type: 'transform', question: 'She will have read the book. (Question)', correctAnswer: 'Will she have read the book?' },
      { type: 'mcq', question: 'By 2030, scientists ___ discovered a cure.', options: ['will have','will has','has','would'], correctAnswer: 'will have' },
      { type: 'error', question: 'He will have wrote the letter.', correctAnswer: 'He will have written the letter.' },
      { type: 'fill', question: 'We ___ (complete) the construction by December.', correctAnswer: 'will have completed' },
    ]
  },
  {
    dayNumber: 9, topic: 'Parts of Speech – Nouns & Pronouns', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Nouns name people, places, things or ideas. Pronouns replace nouns.',
    rules: ['Proper nouns are capitalized', 'Personal pronouns: I, you, he, she, it, we, they', 'Use "who" for people, "which" for things'],
    examples: ['Ram is a student. He is intelligent.', 'Delhi is a city. It is beautiful.'],
    commonMistakes: ['Wrong pronoun case (I vs me)', 'Capitalizing common nouns'],
    questions: [
      { type: 'mcq', question: 'Which is a proper noun?', options: ['city','river','Kolkata','school'], correctAnswer: 'Kolkata' },
      { type: 'fill', question: 'Anita is my friend. ___ is very kind.', correctAnswer: 'She' },
      { type: 'mcq', question: '___ is better to arrive early.', options: ['He','It','They','She'], correctAnswer: 'It' },
      { type: 'error', question: 'Him went to the market.', correctAnswer: 'He went to the market.' },
      { type: 'mcq', question: 'The book is on the table. ___ is interesting.', options: ['He','She','It','They'], correctAnswer: 'It' },
      { type: 'fill', question: 'Ravi and Sam are friends. ___ play together.', correctAnswer: 'They' },
      { type: 'transform', question: 'Replace the noun: "The children played."', correctAnswer: 'They played.' },
      { type: 'mcq', question: 'Which word is an abstract noun?', options: ['table','love','Ravi','cat'], correctAnswer: 'love' },
      { type: 'error', question: 'Me and my brother went to delhi.', correctAnswer: 'My brother and I went to Delhi.' },
      { type: 'fill', question: 'This is Rina\'s pen. It belongs to ___.', correctAnswer: 'her' },
    ]
  },
  {
    dayNumber: 10, topic: 'Parts of Speech – Adjectives & Adverbs', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Adjectives describe nouns. Adverbs describe verbs, adjectives or other adverbs.',
    rules: ['Adjectives come before nouns or after linking verbs', 'Adverbs often end in -ly', 'Use comparative/superlative forms correctly'],
    examples: ['She is a beautiful girl. (adjective)', 'She sings beautifully. (adverb)'],
    commonMistakes: ['Using adjective instead of adverb after action verbs', 'Wrong comparative forms'],
    questions: [
      { type: 'mcq', question: 'She sang ___ at the concert.', options: ['beautiful','beautifully','more beautiful','beauty'], correctAnswer: 'beautifully' },
      { type: 'fill', question: 'He is a ___ (tall) boy. He is the ___ (tall) in the class.', correctAnswer: 'tall, tallest' },
      { type: 'mcq', question: 'Which is an adjective?', options: ['quickly','beautiful','run','slowly'], correctAnswer: 'beautiful' },
      { type: 'error', question: 'She speaks very fastly.', correctAnswer: 'She speaks very fast.' },
      { type: 'transform', question: 'Positive: She is tall. (Comparative)', correctAnswer: 'She is taller than others.' },
      { type: 'fill', question: 'The mango is ___ (sweet) than the lemon.', correctAnswer: 'sweeter' },
      { type: 'mcq', question: 'He runs ___.', options: ['quick','quickly','quicker','quickest'], correctAnswer: 'quickly' },
      { type: 'error', question: 'She is more taller than her sister.', correctAnswer: 'She is taller than her sister.' },
      { type: 'fill', question: 'This is the ___ (good) book I have ever read.', correctAnswer: 'best' },
      { type: 'mcq', question: 'The old man walks ___.', options: ['slow','slowly','slowful','slowing'], correctAnswer: 'slowly' },
    ]
  },
  {
    dayNumber: 11, topic: 'Assertive Sentences', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Assertive (declarative) sentences make a statement. They end with a full stop.',
    rules: ['Subject + Verb + Object structure', 'Affirmative asserts a fact', 'Negative asserts the opposite using not'],
    examples: ['The earth revolves around the sun.', 'She does not like cold coffee.'],
    commonMistakes: ['Using question word order in statements', 'Missing full stop'],
    questions: [
      { type: 'mcq', question: 'Which is an assertive sentence?', options: ['Is she coming?','Come here!','She is coming.','What a day!'], correctAnswer: 'She is coming.' },
      { type: 'fill', question: 'She ___ (live) in Mumbai. (assertive)', correctAnswer: 'lives' },
      { type: 'transform', question: '"Is he your brother?" — Change to assertive.', correctAnswer: 'He is your brother.' },
      { type: 'error', question: 'The sun rise in the east.', correctAnswer: 'The sun rises in the east.' },
      { type: 'mcq', question: 'Assertive sentences end with:', options: ['?','!','.','...'], correctAnswer: '.' },
      { type: 'fill', question: 'I ___ (not/know) the answer. (negative assertive)', correctAnswer: 'do not know' },
      { type: 'transform', question: '"How beautiful she is!" — Make it assertive.', correctAnswer: 'She is very beautiful.' },
      { type: 'error', question: 'He go to school by bus.', correctAnswer: 'He goes to school by bus.' },
      { type: 'mcq', question: 'A negative assertive uses:', options: ['not','no','never','all of these can'], correctAnswer: 'all of these can' },
      { type: 'fill', question: 'Riya ___ (pass) all her exams last year.', correctAnswer: 'passed' },
    ]
  },
  {
    dayNumber: 12, topic: 'Negative Sentences', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Negative sentences deny or contradict something. They use not, no, never, etc.',
    rules: ['Use do not/does not for simple present', 'Use did not for simple past', 'Use will not for future', 'Use is not/are not/was not/were not with continuous forms'],
    examples: ['She does not play cricket.', 'They did not finish the work.', 'He will not come today.'],
    commonMistakes: ['Using V2 after "did not"', 'Double negatives'],
    questions: [
      { type: 'transform', question: 'He plays guitar. (Negative)', correctAnswer: 'He does not play guitar.' },
      { type: 'fill', question: 'She ___ (not/go) to school yesterday.', correctAnswer: 'did not go' },
      { type: 'transform', question: 'They will attend the meeting. (Negative)', correctAnswer: 'They will not attend the meeting.' },
      { type: 'error', question: 'He did not went to school.', correctAnswer: 'He did not go to school.' },
      { type: 'mcq', question: 'She ___ like coffee.', options: ['do not','does not','did not','is not'], correctAnswer: 'does not' },
      { type: 'fill', question: 'We ___ (not/see) each other for years.', correctAnswer: 'have not seen' },
      { type: 'transform', question: 'I am reading. (Negative)', correctAnswer: 'I am not reading.' },
      { type: 'error', question: 'She doesn\'t knows the answer.', correctAnswer: 'She doesn\'t know the answer.' },
      { type: 'mcq', question: 'Which is a correct negative sentence?', options: ['He not eat.','He does not eats.','He does not eat.','He do not eat.'], correctAnswer: 'He does not eat.' },
      { type: 'fill', question: 'They ___ (not/finish) the project yet.', correctAnswer: 'have not finished' },
    ]
  },
  {
    dayNumber: 13, topic: 'Interrogative Sentences', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Interrogative sentences ask a question. They end with a question mark.',
    rules: ['Yes/No questions: Do/Does/Did/Is/Are/Was/Were + Subject + Verb', 'Wh- questions: Wh-word + Auxiliary + Subject + Verb', 'Always end with ?'],
    examples: ['Does she play cricket?', 'Where are you going?', 'What did he say?'],
    commonMistakes: ['Wrong auxiliary verb', 'Forgetting ?', 'Wrong word order in Wh- questions'],
    questions: [
      { type: 'transform', question: 'She plays guitar. (Question)', correctAnswer: 'Does she play guitar?' },
      { type: 'fill', question: '___ you coming to the party?', correctAnswer: 'Are' },
      { type: 'transform', question: 'He went to school. (Question)', correctAnswer: 'Did he go to school?' },
      { type: 'error', question: 'Where she is going?', correctAnswer: 'Where is she going?' },
      { type: 'mcq', question: 'Which is a correct interrogative?', options: ['She does play?','Does she plays?','Does she play?','She play?'], correctAnswer: 'Does she play?' },
      { type: 'fill', question: '___ did you go yesterday?', correctAnswer: 'Where' },
      { type: 'transform', question: 'They have finished the work. (Question)', correctAnswer: 'Have they finished the work?' },
      { type: 'error', question: 'What you are doing?', correctAnswer: 'What are you doing?' },
      { type: 'mcq', question: 'Interrogative sentences end with:', options: ['.',',','?','!'], correctAnswer: '?' },
      { type: 'fill', question: '___ is your name?', correctAnswer: 'What' },
    ]
  },
  {
    dayNumber: 14, topic: 'Exclamatory Sentences', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Exclamatory sentences express strong emotions and end with an exclamation mark.',
    rules: ['Start with What or How', 'What + a/an + adjective + noun + subject + verb', 'How + adjective/adverb + subject + verb'],
    examples: ['What a beautiful flower it is!', 'How cleverly she solved the puzzle!'],
    commonMistakes: ['Wrong article usage (a/an)', 'Using What with adverbs', 'Using How with noun phrases'],
    questions: [
      { type: 'transform', question: 'She is very beautiful. (Exclamatory)', correctAnswer: 'How beautiful she is!' },
      { type: 'fill', question: '___ a wonderful idea it is!', correctAnswer: 'What' },
      { type: 'transform', question: 'It is a very hot day. (Exclamatory)', correctAnswer: 'What a hot day it is!' },
      { type: 'error', question: 'What a she sings beautifully!', correctAnswer: 'How beautifully she sings!' },
      { type: 'mcq', question: 'Exclamatory sentences end with:', options: ['.',',','?','!'], correctAnswer: '!' },
      { type: 'fill', question: '___ fast he runs!', correctAnswer: 'How' },
      { type: 'transform', question: 'She is very intelligent. (Exclamatory using What)', correctAnswer: 'What an intelligent girl she is!' },
      { type: 'error', question: 'How a beautiful garden it is!', correctAnswer: 'What a beautiful garden it is!' },
      { type: 'mcq', question: '"What a brave soldier he is!" — The adjective is:', options: ['What','soldier','brave','he'], correctAnswer: 'brave' },
      { type: 'fill', question: 'What ___ honest man he is!', correctAnswer: 'an' },
    ]
  },
  {
    dayNumber: 15, topic: 'Simple Sentences', difficulty: 'medium', timeLimit: 1800,
    explanation: 'A simple sentence has one independent clause with one subject and one predicate.',
    rules: ['One subject + one predicate', 'No conjunction joining two independent clauses', 'Can have compound subject or compound predicate'],
    examples: ['She reads.', 'Ram and Shyam play cricket.', 'She reads and writes well.'],
    commonMistakes: ['Confusing simple sentence with simple tense', 'Adding extra clauses'],
    questions: [
      { type: 'mcq', question: 'Which is a simple sentence?', options: ['She sings and dances.','She sings, and he dances.','She sings because she loves music.','Although she sings, she dances.'], correctAnswer: 'She sings and dances.' },
      { type: 'fill', question: 'The boy ___ (run) fast. (simple sentence)', correctAnswer: 'runs' },
      { type: 'transform', question: '"She went to market and bought vegetables." Identify the type.', correctAnswer: 'Simple sentence' },
      { type: 'error', question: 'Ram goes to school and he learns.', correctAnswer: 'Ram goes to school and learns.' },
      { type: 'mcq', question: 'A simple sentence has ___ independent clause(s).', options: ['one','two','three','more than one'], correctAnswer: 'one' },
      { type: 'fill', question: 'Ravi and Raju ___ (be) best friends. (simple sentence)', correctAnswer: 'are' },
      { type: 'transform', question: 'Rewrite as simple sentence: "He is strong. He is brave."', correctAnswer: 'He is strong and brave.' },
      { type: 'error', question: 'The children plays and they laugh.', correctAnswer: 'The children play and laugh.' },
      { type: 'mcq', question: '"Birds sing and build nests." This sentence has:', options: ['one subject and two predicates','two subjects','two clauses','one predicate'], correctAnswer: 'one subject and two predicates' },
      { type: 'fill', question: 'She danced and ___ (sing) at the function.', correctAnswer: 'sang' },
    ]
  },
  {
    dayNumber: 16, topic: 'Compound Sentences', difficulty: 'medium', timeLimit: 1800,
    explanation: 'A compound sentence joins two or more independent clauses using coordinating conjunctions (FANBOYS): for, and, nor, but, or, yet, so.',
    rules: ['Join two independent clauses with a conjunction', 'Use a comma before the conjunction', 'Common conjunctions: and, but, or, so, yet, for'],
    examples: ['She was tired, but she continued working.', 'He studied hard, so he passed the exam.'],
    commonMistakes: ['Missing comma before conjunction', 'Using subordinating conjunctions instead'],
    questions: [
      { type: 'mcq', question: 'Which is a compound sentence?', options: ['She came early.','She came early because she wanted to.','She came early, and she helped us.','Although she came early, she left soon.'], correctAnswer: 'She came early, and she helped us.' },
      { type: 'fill', question: 'He was hungry, ___ he ate a lot.', correctAnswer: 'so' },
      { type: 'transform', question: 'Combine: "She is clever. She works hard."', correctAnswer: 'She is clever, and she works hard.' },
      { type: 'error', question: 'He is smart but he always fail.', correctAnswer: 'He is smart, but he always fails.' },
      { type: 'mcq', question: 'Coordinating conjunctions include:', options: ['because','although','and','since'], correctAnswer: 'and' },
      { type: 'fill', question: 'It was raining, ___ they stayed indoors.', correctAnswer: 'so' },
      { type: 'transform', question: 'Combine: "Study hard. You will pass."', correctAnswer: 'Study hard, or you will not pass.' },
      { type: 'error', question: 'She is tired but she does not stopping.', correctAnswer: 'She is tired, but she does not stop.' },
      { type: 'mcq', question: 'In a compound sentence, the clauses are joined by:', options: ['subordinating conjunction','coordinating conjunction','relative pronoun','preposition'], correctAnswer: 'coordinating conjunction' },
      { type: 'fill', question: 'I wanted to help, ___ I was too busy.', correctAnswer: 'but' },
    ]
  },
  {
    dayNumber: 17, topic: 'Complex Sentences', difficulty: 'medium', timeLimit: 1800,
    explanation: 'A complex sentence has one independent clause and one or more dependent (subordinate) clauses.',
    rules: ['Use subordinating conjunctions: because, although, when, if, since, as, unless', 'Dependent clause cannot stand alone', 'Comma after dependent clause when it comes first'],
    examples: ['Although she was tired, she continued working.', 'He will pass if he studies hard.'],
    commonMistakes: ['Treating dependent clause as full sentence', 'Missing comma when clause comes first'],
    questions: [
      { type: 'mcq', question: 'Which is a complex sentence?', options: ['She sings and dances.','She sings, and he dances.','She sings because she is happy.','She sings well.'], correctAnswer: 'She sings because she is happy.' },
      { type: 'fill', question: '___ it rains, the match will be cancelled.', correctAnswer: 'If' },
      { type: 'transform', question: 'Combine: "She was ill. She went to school."', correctAnswer: 'Although she was ill, she went to school.' },
      { type: 'error', question: 'Because she was late. She missed the bus.', correctAnswer: 'Because she was late, she missed the bus.' },
      { type: 'mcq', question: 'Subordinating conjunctions include:', options: ['and','but','although','or'], correctAnswer: 'although' },
      { type: 'fill', question: 'He will succeed ___ he works hard.', correctAnswer: 'if' },
      { type: 'transform', question: 'Combine: "He finished the work. He went home."', correctAnswer: 'After he finished the work, he went home.' },
      { type: 'error', question: 'When she arrive, I will call you.', correctAnswer: 'When she arrives, I will call you.' },
      { type: 'mcq', question: 'The dependent clause in a complex sentence:', options: ['can stand alone','starts with a coordinating conjunction','cannot stand alone','is always at the end'], correctAnswer: 'cannot stand alone' },
      { type: 'fill', question: '___ the lesson was difficult, she understood it.', correctAnswer: 'Although' },
    ]
  },
  {
    dayNumber: 18, topic: 'Active Voice', difficulty: 'medium', timeLimit: 1800,
    explanation: 'In Active Voice, the subject performs the action.',
    rules: ['Subject + Verb + Object', 'The subject is the doer', 'Active voice is more direct and clear'],
    examples: ['She wrote the letter.', 'The dog chased the cat.', 'Ram reads books.'],
    commonMistakes: ['Confusing active with passive', 'Wrong verb form'],
    questions: [
      { type: 'mcq', question: 'Which sentence is in active voice?', options: ['The letter was written by her.','She wrote the letter.','The cake was eaten.','Mistakes were made.'], correctAnswer: 'She wrote the letter.' },
      { type: 'fill', question: 'The teacher ___ (explain) the lesson. (active)', correctAnswer: 'explained' },
      { type: 'transform', question: 'Change to active: "The ball was kicked by Ram."', correctAnswer: 'Ram kicked the ball.' },
      { type: 'error', question: 'The boy was run fast.', correctAnswer: 'The boy ran fast.' },
      { type: 'mcq', question: 'In active voice, the subject is the:', options: ['receiver','doer','object','none'], correctAnswer: 'doer' },
      { type: 'fill', question: 'She ___ (cook) dinner every evening. (active)', correctAnswer: 'cooks' },
      { type: 'transform', question: 'Change to active: "The song was sung by Asha."', correctAnswer: 'Asha sang the song.' },
      { type: 'error', question: 'He is written a novel.', correctAnswer: 'He is writing a novel.' },
      { type: 'mcq', question: '"Birds eat worms." The verb is in ___ voice.', options: ['passive','active','perfect','none'], correctAnswer: 'active' },
      { type: 'fill', question: 'The students ___ (complete) the task. (active)', correctAnswer: 'completed' },
    ]
  },
  {
    dayNumber: 19, topic: 'Passive Voice', difficulty: 'medium', timeLimit: 1800,
    explanation: 'In Passive Voice, the subject receives the action. The focus is on the action or object.',
    rules: ['Object + be verb + V3 (+ by + subject)', 'Use appropriate form of "be" based on tense', 'The doer (agent) is introduced with "by"'],
    examples: ['The letter was written by her.', 'The cake is being eaten.', 'The match will be played.'],
    commonMistakes: ['Wrong tense of "be"', 'Using V2 instead of V3', 'Omitting "by"'],
    questions: [
      { type: 'mcq', question: 'Which is in passive voice?', options: ['She sings a song.','A song is sung by her.','He plays cricket.','They go to school.'], correctAnswer: 'A song is sung by her.' },
      { type: 'transform', question: 'Change to passive: "She wrote the letter."', correctAnswer: 'The letter was written by her.' },
      { type: 'fill', question: 'The book ___ (write) by Tagore. (passive)', correctAnswer: 'was written' },
      { type: 'error', question: 'The cake was ate by the children.', correctAnswer: 'The cake was eaten by the children.' },
      { type: 'transform', question: 'Change to passive: "They will finish the project."', correctAnswer: 'The project will be finished by them.' },
      { type: 'mcq', question: 'In passive voice, V3 is used with:', options: ['do/does','will','be verb','have/has'], correctAnswer: 'be verb' },
      { type: 'fill', question: 'The road ___ (repair) by the workers. (passive, present)', correctAnswer: 'is being repaired' },
      { type: 'transform', question: 'Change to passive: "Ram eats mangoes."', correctAnswer: 'Mangoes are eaten by Ram.' },
      { type: 'error', question: 'The letter is write by her.', correctAnswer: 'The letter is written by her.' },
      { type: 'fill', question: 'A new school ___ (build) in our town. (passive, future)', correctAnswer: 'will be built' },
    ]
  },
  {
    dayNumber: 20, topic: 'Direct Speech', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Direct Speech reports the exact words of a speaker, enclosed in quotation marks.',
    rules: ['Use inverted commas (" ")', 'Comma separates the reporting verb from the speech', 'Capital letter at the start of direct speech'],
    examples: ['She said, "I am happy."', 'He asked, "Where are you going?"'],
    commonMistakes: ['Missing inverted commas', 'Wrong punctuation', 'Not capitalizing first word of speech'],
    questions: [
      { type: 'mcq', question: 'Which is direct speech?', options: ['She said she was happy.','She said, "I am happy."','She told that she is happy.','She mentioned being happy.'], correctAnswer: 'She said, "I am happy."' },
      { type: 'fill', question: 'He said, "___ are you doing?" (What/How)', correctAnswer: 'What' },
      { type: 'transform', question: 'Indirect: She said she was tired. → Direct', correctAnswer: 'She said, "I am tired."' },
      { type: 'error', question: 'He said "i will come tomorrow".', correctAnswer: 'He said, "I will come tomorrow."' },
      { type: 'mcq', question: 'In direct speech, the exact words are placed in:', options: ['brackets','inverted commas','italics','bold'], correctAnswer: 'inverted commas' },
      { type: 'fill', question: 'She said, "___ is my birthday today."', correctAnswer: 'It' },
      { type: 'transform', question: 'Indirect: He told me he loved cricket. → Direct', correctAnswer: 'He said, "I love cricket."' },
      { type: 'error', question: 'She asked, "where are you going"?', correctAnswer: 'She asked, "Where are you going?"' },
      { type: 'mcq', question: 'The reporting verb in "She said, \'I am fine.\'" is:', options: ['am','fine','said','she'], correctAnswer: 'said' },
      { type: 'fill', question: 'He said, "___ won the match!" (We/They)', correctAnswer: 'We' },
    ]
  },
  {
    dayNumber: 21, topic: 'Indirect Speech', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Indirect (Reported) Speech reports what someone said without using their exact words.',
    rules: ['Change pronouns appropriately', 'Change tense (backshift): present → past', 'Remove inverted commas', 'Use "that" after said/told for statements'],
    examples: ['Direct: "I am happy." → Indirect: She said that she was happy.'],
    commonMistakes: ['Not backshifting tense', 'Wrong pronoun change', 'Keeping inverted commas'],
    questions: [
      { type: 'transform', question: 'Direct: She said, "I am hungry." → Indirect', correctAnswer: 'She said that she was hungry.' },
      { type: 'fill', question: 'He said, "I will come." → He said that he ___ come.', correctAnswer: 'would' },
      { type: 'transform', question: 'Direct: "They play cricket." → Indirect', correctAnswer: 'He said that they played cricket.' },
      { type: 'error', question: 'She said that she is happy.', correctAnswer: 'She said that she was happy.' },
      { type: 'mcq', question: 'In indirect speech, "will" changes to:', options: ['shall','would','could','should'], correctAnswer: 'would' },
      { type: 'fill', question: 'He said, "I have finished." → He said that he ___ finished.', correctAnswer: 'had' },
      { type: 'transform', question: 'Direct: "We are leaving." → Indirect', correctAnswer: 'She said that they were leaving.' },
      { type: 'error', question: 'She told me that she will go.', correctAnswer: 'She told me that she would go.' },
      { type: 'mcq', question: '"Am/is/are" changes to ___ in indirect speech.', options: ['was/were','will','would','had'], correctAnswer: 'was/were' },
      { type: 'fill', question: 'She said, "I can swim." → She said that she ___ swim.', correctAnswer: 'could' },
    ]
  },
  {
    dayNumber: 22, topic: 'Articles – A, An, The', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Articles (a, an, the) are used before nouns. "A" and "an" are indefinite; "the" is definite.',
    rules: ['Use "a" before consonant sounds', 'Use "an" before vowel sounds', 'Use "the" for specific/known nouns', 'No article for general plurals or uncountable nouns in general sense'],
    examples: ['She is a doctor.', 'He ate an apple.', 'The sun rises in the east.'],
    commonMistakes: ['Using "a" before vowel sounds', 'Using "the" unnecessarily', 'Omitting "the" before specific nouns'],
    questions: [
      { type: 'fill', question: 'She is ___ honest woman.', correctAnswer: 'an' },
      { type: 'mcq', question: 'Use ___ before "umbrella".', options: ['a','an','the','no article'], correctAnswer: 'an' },
      { type: 'fill', question: '___ sun rises in the east.', correctAnswer: 'The' },
      { type: 'error', question: 'He is a honest man.', correctAnswer: 'He is an honest man.' },
      { type: 'mcq', question: '"___ Taj Mahal is beautiful." Which article fits?', options: ['A','An','The','No article'], correctAnswer: 'The' },
      { type: 'fill', question: 'I saw ___ elephant at the zoo.', correctAnswer: 'an' },
      { type: 'transform', question: 'Fill: "___ gold is a precious metal."', correctAnswer: 'No article needed – Gold is a precious metal.' },
      { type: 'error', question: 'She plays a piano.', correctAnswer: 'She plays the piano.' },
      { type: 'mcq', question: 'Which sentence is correct?', options: ['I need a advice.','I need an advice.','I need advice.','I need the advices.'], correctAnswer: 'I need advice.' },
      { type: 'fill', question: 'He is ___ university student.', correctAnswer: 'a' },
    ]
  },
  {
    dayNumber: 23, topic: 'Prepositions', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Prepositions show the relationship between a noun/pronoun and other words in a sentence.',
    rules: ['Prepositions of place: in, on, at, under, above, between', 'Prepositions of time: in, on, at, since, for, by', 'Prepositions of direction: to, from, towards, into'],
    examples: ['She is sitting on the chair.', 'The meeting is at 5 PM.', 'He has lived here since 2010.'],
    commonMistakes: ['Confusing in/on/at for time and place', 'Wrong preposition with verbs'],
    questions: [
      { type: 'fill', question: 'She arrived ___ Monday.', correctAnswer: 'on' },
      { type: 'mcq', question: 'The book is ___ the table.', options: ['in','at','on','by'], correctAnswer: 'on' },
      { type: 'fill', question: 'He has been working here ___ 2015.', correctAnswer: 'since' },
      { type: 'error', question: 'She is good in singing.', correctAnswer: 'She is good at singing.' },
      { type: 'mcq', question: 'They met ___ the park.', options: ['in','at','on','into'], correctAnswer: 'in' },
      { type: 'fill', question: 'The exam is ___ 10 AM.', correctAnswer: 'at' },
      { type: 'transform', question: 'Fill the blank: "He was born ___ 1999."', correctAnswer: 'in' },
      { type: 'error', question: 'She is married with a doctor.', correctAnswer: 'She is married to a doctor.' },
      { type: 'mcq', question: 'We go to school ___ foot.', options: ['by','on','at','in'], correctAnswer: 'on' },
      { type: 'fill', question: 'She jumped ___ the pool.', correctAnswer: 'into' },
    ]
  },
  {
    dayNumber: 24, topic: 'Conjunctions', difficulty: 'easy', timeLimit: 1800,
    explanation: 'Conjunctions join words, phrases or clauses.',
    rules: ['Coordinating: and, but, or, so, yet, for, nor', 'Subordinating: because, although, when, if, since, unless', 'Correlative: either...or, neither...nor, both...and, not only...but also'],
    examples: ['She is smart and hard-working.', 'He failed because he did not study.', 'Either she or her brother will come.'],
    commonMistakes: ['Confusing coordinating and subordinating conjunctions', 'Wrong correlative pair'],
    questions: [
      { type: 'fill', question: 'He was tired, ___ he continued working.', correctAnswer: 'but' },
      { type: 'mcq', question: 'Which is a subordinating conjunction?', options: ['and','but','because','or'], correctAnswer: 'because' },
      { type: 'fill', question: '___ she was late, she missed the bus.', correctAnswer: 'Because' },
      { type: 'error', question: 'Neither he or she came.', correctAnswer: 'Neither he nor she came.' },
      { type: 'mcq', question: '"Both Ram ___ Shyam play football." Fill in:', options: ['or','and','nor','but'], correctAnswer: 'and' },
      { type: 'fill', question: 'You will fail ___ you work hard.', correctAnswer: 'unless' },
      { type: 'transform', question: 'Join: "She is poor. She is happy."', correctAnswer: 'She is poor but she is happy.' },
      { type: 'error', question: 'She is not only smart but also works hard.', correctAnswer: 'She is not only smart but also hardworking.' },
      { type: 'mcq', question: '"She will come ___ she is invited." Fill in:', options: ['but','if','and','because'], correctAnswer: 'if' },
      { type: 'fill', question: 'Either you leave ___ I will call the police.', correctAnswer: 'or' },
    ]
  },
  {
    dayNumber: 25, topic: 'Modals – Can, Could, May, Might', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Modal verbs express ability, possibility, permission, or probability.',
    rules: ['Can = ability/permission (present)', 'Could = ability/possibility (past or polite)', 'May = formal permission/possibility', 'Might = less certain possibility'],
    examples: ['She can swim.', 'Could you help me?', 'It may rain.', 'He might come.'],
    commonMistakes: ['Using "can" for formal permission (use "may")', 'Adding -s to modal verbs', 'Using infinitive with "to" after modals'],
    questions: [
      { type: 'mcq', question: 'She ___ speak three languages.', options: ['can','cans','is able','could to'], correctAnswer: 'can' },
      { type: 'fill', question: '___ I use your pen? (polite)', correctAnswer: 'May' },
      { type: 'mcq', question: 'It ___ rain this evening. (possibility)', options: ['can','might','shall','must'], correctAnswer: 'might' },
      { type: 'error', question: 'She mights come to the party.', correctAnswer: 'She might come to the party.' },
      { type: 'transform', question: '"Can she swim?" — Make it more polite.', correctAnswer: 'Could she swim?' },
      { type: 'fill', question: 'When I was young, I ___ run very fast.', correctAnswer: 'could' },
      { type: 'mcq', question: '"___ I come in?" — Formal permission:', options: ['Can','Could','May','Might'], correctAnswer: 'May' },
      { type: 'error', question: 'He can to play the guitar.', correctAnswer: 'He can play the guitar.' },
      { type: 'fill', question: 'She ___ be at home; I\'m not sure.', correctAnswer: 'might' },
      { type: 'mcq', question: 'Which shows past ability?', options: ['can','may','could','might'], correctAnswer: 'could' },
    ]
  },
  {
    dayNumber: 26, topic: 'Modals – Must, Should, Ought to, Need', difficulty: 'medium', timeLimit: 1800,
    explanation: 'These modals express obligation, advice, necessity or logical deduction.',
    rules: ['Must = strong obligation/certainty', 'Should = advice/mild obligation', 'Ought to = moral obligation', 'Need = necessity (need not = no necessity)'],
    examples: ['You must wear a seatbelt.', 'You should exercise daily.', 'You ought to respect elders.', 'You need not come.'],
    commonMistakes: ['Confusing must and should', 'Adding "to" after must/should', 'Using "must not" for unnecessary action (use "need not")'],
    questions: [
      { type: 'mcq', question: 'You ___ obey traffic rules.', options: ['should','ought to','must','all of these'], correctAnswer: 'all of these' },
      { type: 'fill', question: 'She ___ not come; it is not necessary.', correctAnswer: 'need' },
      { type: 'mcq', question: 'You ___ brush your teeth twice a day. (advice)', options: ['must','should','can','might'], correctAnswer: 'should' },
      { type: 'error', question: 'You must to finish this work.', correctAnswer: 'You must finish this work.' },
      { type: 'transform', question: '"You must not eat here." — Meaning:', correctAnswer: 'It is forbidden to eat here.' },
      { type: 'fill', question: 'He ___ to help the poor. (moral duty)', correctAnswer: 'ought' },
      { type: 'mcq', question: 'She looks pale. She ___ be ill. (deduction)', options: ['can','should','must','would'], correctAnswer: 'must' },
      { type: 'error', question: 'She should to study more.', correctAnswer: 'She should study more.' },
      { type: 'fill', question: 'You ___ not worry; everything is fine.', correctAnswer: 'need' },
      { type: 'mcq', question: '"Need not" means:', options: ['forbidden','not necessary','not possible','not allowed'], correctAnswer: 'not necessary' },
    ]
  },
  {
    dayNumber: 27, topic: 'Conditionals – Zero & First', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Zero Conditional: general truths. First Conditional: real/possible future situations.',
    rules: ['Zero: If + present simple, present simple', 'First: If + present simple, will + base verb', 'The "if" clause can come first or second'],
    examples: ['If you heat water, it boils. (Zero)', 'If she studies, she will pass. (First)'],
    commonMistakes: ['Using "will" in the if-clause (First)', 'Mixing up zero and first conditionals'],
    questions: [
      { type: 'mcq', question: '"If you mix red and blue, you ___ purple." (Zero)', options: ['will get','get','got','getting'], correctAnswer: 'get' },
      { type: 'fill', question: 'If it rains, the match ___ (cancel). (First)', correctAnswer: 'will be cancelled' },
      { type: 'mcq', question: 'First conditional uses ___ in the result clause.', options: ['would','will','can','might'], correctAnswer: 'will' },
      { type: 'error', question: 'If she will come, I will tell her.', correctAnswer: 'If she comes, I will tell her.' },
      { type: 'transform', question: 'Make First Conditional: "She studies / She passes"', correctAnswer: 'If she studies, she will pass.' },
      { type: 'fill', question: 'If you touch fire, you ___ (burn). (Zero)', correctAnswer: 'burn' },
      { type: 'mcq', question: 'Zero conditional is used for:', options: ['unlikely events','general truths','past habits','wishes'], correctAnswer: 'general truths' },
      { type: 'error', question: 'If he will study hard, he will pass.', correctAnswer: 'If he studies hard, he will pass.' },
      { type: 'fill', question: 'If I see her, I ___ (give) her the message. (First)', correctAnswer: 'will give' },
      { type: 'mcq', question: '"If plants don\'t get water, they die." This is ___ conditional.', options: ['first','second','zero','third'], correctAnswer: 'zero' },
    ]
  },
  {
    dayNumber: 28, topic: 'Conditionals – Second & Third', difficulty: 'hard', timeLimit: 1800,
    explanation: 'Second Conditional: hypothetical/unreal present. Third Conditional: hypothetical past.',
    rules: ['Second: If + past simple, would + base verb', 'Third: If + past perfect, would have + V3', 'Second = imaginary now; Third = imaginary past'],
    examples: ['If I were rich, I would travel. (Second)', 'If she had studied, she would have passed. (Third)'],
    commonMistakes: ['Using "was" instead of "were" (second)', 'Missing "have" in third conditional'],
    questions: [
      { type: 'mcq', question: '"If I ___ a bird, I would fly." (Second)', options: ['am','was','were','will be'], correctAnswer: 'were' },
      { type: 'fill', question: 'If she had tried, she ___ (succeed). (Third)', correctAnswer: 'would have succeeded' },
      { type: 'mcq', question: 'Second conditional result clause uses:', options: ['will','would','would have','could have'], correctAnswer: 'would' },
      { type: 'error', question: 'If I was a king, I would help the poor.', correctAnswer: 'If I were a king, I would help the poor.' },
      { type: 'transform', question: 'Make Third: "She didn\'t study / She failed"', correctAnswer: 'If she had studied, she would not have failed.' },
      { type: 'fill', question: 'If he had come, we ___ (meet) him. (Third)', correctAnswer: 'would have met' },
      { type: 'mcq', question: 'Which is a third conditional?', options: ['If she studies, she will pass.','If she studied, she would pass.','If she had studied, she would have passed.','If she studies, she passes.'], correctAnswer: 'If she had studied, she would have passed.' },
      { type: 'error', question: 'If they had work harder, they would have won.', correctAnswer: 'If they had worked harder, they would have won.' },
      { type: 'fill', question: 'If I were you, I ___ (not/do) that. (Second)', correctAnswer: 'would not do' },
      { type: 'mcq', question: 'Third conditional refers to:', options: ['present unreal','future possible','past unreal','general truth'], correctAnswer: 'past unreal' },
    ]
  },
  {
    dayNumber: 29, topic: 'Question Tags', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Question tags are short questions added at the end of statements to confirm or check information.',
    rules: ['Positive statement + negative tag', 'Negative statement + positive tag', 'Match auxiliary verb of main sentence', 'Subject in tag is always a pronoun'],
    examples: ['She is coming, isn\'t she?', 'They didn\'t go, did they?', 'He can swim, can\'t he?'],
    commonMistakes: ['Using same auxiliary as statement in same polarity', 'Using noun instead of pronoun in tag', 'Wrong auxiliary verb'],
    questions: [
      { type: 'fill', question: 'She is happy, ___ she?', correctAnswer: 'isn\'t' },
      { type: 'mcq', question: 'They went to school, ___ they?', options: ['did','didn\'t','do','don\'t'], correctAnswer: 'didn\'t' },
      { type: 'fill', question: 'He can swim, ___ he?', correctAnswer: 'can\'t' },
      { type: 'error', question: 'She plays well, doesn\'t she play?', correctAnswer: 'She plays well, doesn\'t she?' },
      { type: 'mcq', question: 'You haven\'t eaten, ___ you?', options: ['have','haven\'t','did','didn\'t'], correctAnswer: 'have' },
      { type: 'fill', question: 'It is raining, ___ it?', correctAnswer: 'isn\'t' },
      { type: 'transform', question: 'Add tag: "She will come."', correctAnswer: 'She will come, won\'t she?' },
      { type: 'error', question: 'Ram works hard, doesn\'t Ram?', correctAnswer: 'Ram works hard, doesn\'t he?' },
      { type: 'mcq', question: 'I am your friend, ___ I?', options: ['amn\'t','aren\'t','isn\'t','wasn\'t'], correctAnswer: 'aren\'t' },
      { type: 'fill', question: 'They were playing, ___ they?', correctAnswer: 'weren\'t' },
    ]
  },
  {
    dayNumber: 30, topic: 'Reported Speech – Questions', difficulty: 'hard', timeLimit: 1800,
    explanation: 'When reporting questions in indirect speech, word order becomes statement-like (no inversion).',
    rules: ['Yes/No questions: use "if" or "whether"', 'Wh-questions: use the wh-word', 'No question mark in reported questions', 'Change tense (backshift)'],
    examples: ['Direct: "Where are you going?" → Indirect: She asked where I was going.'],
    commonMistakes: ['Keeping question mark', 'Not changing word order', 'Not backshifting tense'],
    questions: [
      { type: 'transform', question: 'Direct: "Are you hungry?" → Indirect', correctAnswer: 'She asked if I was hungry.' },
      { type: 'fill', question: 'He asked ___ I had finished my work.', correctAnswer: 'if' },
      { type: 'transform', question: 'Direct: "Where do you live?" → Indirect', correctAnswer: 'She asked where I lived.' },
      { type: 'error', question: 'She asked where was I going.', correctAnswer: 'She asked where I was going.' },
      { type: 'mcq', question: 'In reported Yes/No questions, we use:', options: ['that','which','if/whether','what'], correctAnswer: 'if/whether' },
      { type: 'fill', question: 'He asked me ___ I could help him.', correctAnswer: 'if' },
      { type: 'transform', question: 'Direct: "What is your name?" → Indirect', correctAnswer: 'She asked what my name was.' },
      { type: 'error', question: 'She asked that where I had gone.', correctAnswer: 'She asked where I had gone.' },
      { type: 'mcq', question: 'In reported questions, the verb form:', options: ['stays the same','inverts','backshifts','doubles'], correctAnswer: 'backshifts' },
      { type: 'fill', question: 'He asked me ___ I liked coffee.', correctAnswer: 'whether' },
    ]
  },
  {
    dayNumber: 31, topic: 'Transformation of Sentences – Degree', difficulty: 'hard', timeLimit: 1800,
    explanation: 'Sentences can be transformed among Positive, Comparative, and Superlative degrees without changing meaning.',
    rules: ['Positive: as...as', 'Comparative: -er/more...than', 'Superlative: the -est/most', 'No other + noun + is + as + adj + as (Positive = Superlative meaning)'],
    examples: ['She is the tallest in the class. = No other student is as tall as she. = She is taller than any other student.'],
    commonMistakes: ['Changing meaning during transformation', 'Wrong comparative/superlative form'],
    questions: [
      { type: 'transform', question: 'Superlative: "Iron is the most useful metal." → Comparative', correctAnswer: 'Iron is more useful than any other metal.' },
      { type: 'fill', question: 'Comparative: She is taller than any other girl. → Positive: No other girl is ___ tall ___ she.', correctAnswer: 'as, as' },
      { type: 'transform', question: 'Positive: "Gold is as precious as silver." → Comparative', correctAnswer: 'Gold is not less precious than silver.' },
      { type: 'error', question: 'She is more better than her sister.', correctAnswer: 'She is better than her sister.' },
      { type: 'mcq', question: '"He is the best student." Comparative form:', options: ['He is better than all student.','He is better than any other student.','He is best than others.','He is the better student.'], correctAnswer: 'He is better than any other student.' },
      { type: 'fill', question: 'Superlative: Mount Everest is the ___ mountain in the world.', correctAnswer: 'highest' },
      { type: 'transform', question: 'Comparative: "She works harder than anyone else." → Superlative', correctAnswer: 'She works the hardest.' },
      { type: 'error', question: 'He is most tall boy in the class.', correctAnswer: 'He is the tallest boy in the class.' },
      { type: 'mcq', question: 'Positive degree of "better" is:', options: ['best','good','well','gooder'], correctAnswer: 'good' },
      { type: 'fill', question: '"No other city is as big as Mumbai." Change to Superlative: Mumbai is ___ city in India.', correctAnswer: 'the biggest' },
    ]
  },
  {
    dayNumber: 32, topic: 'Transformation – Affirmative & Negative', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Sentences can often be transformed between affirmative and negative forms without changing meaning.',
    rules: ['Use "not...without" for negative of affirmative', 'Use "only" / "never" / "nothing" substitutions', 'Double negatives should be avoided'],
    examples: ['She is always late. = She is never on time.', 'Every student passed. = Not a single student failed.'],
    commonMistakes: ['Changing meaning during transformation', 'Using double negatives incorrectly'],
    questions: [
      { type: 'transform', question: 'Affirmative: "Every student passed." → Negative', correctAnswer: 'Not a single student failed.' },
      { type: 'fill', question: '"She always helps." → "She ___ fails to help."', correctAnswer: 'never' },
      { type: 'transform', question: 'Negative: "He never lies." → Affirmative', correctAnswer: 'He always tells the truth.' },
      { type: 'error', question: 'She doesn\'t never come on time.', correctAnswer: 'She never comes on time.' },
      { type: 'mcq', question: '"Only she can do this." → Negative form:', options: ['She alone can do this.','No one but she can do this.','Only she cannot do this.','Nobody can do this.'], correctAnswer: 'No one but she can do this.' },
      { type: 'fill', question: '"He is too weak to walk." → "He is ___ weak that he cannot walk."', correctAnswer: 'so' },
      { type: 'transform', question: 'Affirmative: "She is the best." → Negative', correctAnswer: 'None is as good as she.' },
      { type: 'error', question: 'No other student is as good as she does.', correctAnswer: 'No other student is as good as she.' },
      { type: 'mcq', question: '"Too tired to walk" means:', options: ['very tired and walks','so tired that she cannot walk','tired but walks','walks though tired'], correctAnswer: 'so tired that she cannot walk' },
      { type: 'fill', question: '"She is rich." → "She is ___ poor."', correctAnswer: 'not' },
    ]
  },
  {
    dayNumber: 33, topic: 'Subject-Verb Agreement', difficulty: 'medium', timeLimit: 1800,
    explanation: 'The verb must agree with the subject in number (singular/plural) and person.',
    rules: ['Singular subject → singular verb (adds -s/-es)', 'Plural subject → plural verb (base form)', 'Collective nouns usually take singular verb', '"Either/Neither" with singular noun → singular verb'],
    examples: ['She plays guitar. (singular)', 'They play guitar. (plural)', 'The team has won.'],
    commonMistakes: ['Verb agrees with nearest noun instead of subject', 'Treating collective noun as plural'],
    questions: [
      { type: 'mcq', question: 'The committee ___ decided.', options: ['have','has','had','are'], correctAnswer: 'has' },
      { type: 'fill', question: 'Neither he nor she ___ (come) to school.', correctAnswer: 'comes' },
      { type: 'mcq', question: 'Each of the boys ___ a prize.', options: ['get','gets','got','getting'], correctAnswer: 'gets' },
      { type: 'error', question: 'The news are shocking.', correctAnswer: 'The news is shocking.' },
      { type: 'transform', question: '"She plays well." Change subject to They.', correctAnswer: 'They play well.' },
      { type: 'fill', question: 'The students along with the teacher ___ (attend) the function.', correctAnswer: 'attend' },
      { type: 'mcq', question: 'Many a student ___ failed the test.', options: ['have','has','had','is'], correctAnswer: 'has' },
      { type: 'error', question: 'Either Ram or his brothers has to come.', correctAnswer: 'Either Ram or his brothers have to come.' },
      { type: 'fill', question: 'Mathematics ___ (be) my favourite subject.', correctAnswer: 'is' },
      { type: 'mcq', question: '"A number of students ___ absent." Fill in:', options: ['is','was','are','has'], correctAnswer: 'are' },
    ]
  },
  {
    dayNumber: 34, topic: 'Tense Revision – Mixed Tenses', difficulty: 'hard', timeLimit: 1800,
    explanation: 'Choosing the correct tense depends on when the action occurs and its nature.',
    rules: ['Simple = completed/habitual action', 'Continuous = ongoing action', 'Perfect = completed before reference point', 'Future forms depend on certainty and plan'],
    examples: ['She has been living here since 2010. (Present Perfect Continuous)', 'By the time he arrives, she will have left. (Future Perfect)'],
    commonMistakes: ['Using simple past instead of present perfect', 'Confusing past perfect and simple past'],
    questions: [
      { type: 'mcq', question: 'She ___ here since 2010. (Present Perfect)', options: ['lives','lived','has lived','had lived'], correctAnswer: 'has lived' },
      { type: 'fill', question: 'By the time he came, she ___ (leave). (Past Perfect)', correctAnswer: 'had left' },
      { type: 'mcq', question: 'I ___ the report when the power went out. (Past Continuous)', options: ['write','wrote','was writing','had written'], correctAnswer: 'was writing' },
      { type: 'error', question: 'She has went to the market.', correctAnswer: 'She has gone to the market.' },
      { type: 'transform', question: '"She will finish by 5 PM." (Future Perfect)', correctAnswer: 'She will have finished by 5 PM.' },
      { type: 'fill', question: 'We ___ (study) for three hours when he arrived.', correctAnswer: 'had been studying' },
      { type: 'mcq', question: 'Which tense: "She has been working for 5 hours."', options: ['Present Perfect','Present Perfect Continuous','Past Perfect','Future Perfect'], correctAnswer: 'Present Perfect Continuous' },
      { type: 'error', question: 'He is knowing the answer.', correctAnswer: 'He knows the answer.' },
      { type: 'fill', question: 'By 2030, scientists ___ (discover) a cure. (Future Perfect)', correctAnswer: 'will have discovered' },
      { type: 'mcq', question: 'She ___ there when I called. (Simple Past)', options: ['is','was','were','has been'], correctAnswer: 'was' },
    ]
  },
  {
    dayNumber: 35, topic: 'Punctuation', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Punctuation marks help organize writing and convey meaning clearly.',
    rules: ['Full stop (.) ends statements', 'Comma (,) separates items/clauses', 'Question mark (?) ends questions', 'Exclamation mark (!) ends exclamations', 'Apostrophe (\'): possession and contractions', 'Colon (:) and semicolon (;) for complex sentences'],
    examples: ['She said, "I am fine."', 'It\'s Ram\'s book.', 'She works hard; she deserves success.'],
    commonMistakes: ['Missing apostrophe in contractions', 'Wrong use of comma before conjunction', 'Mixing up its/it\'s'],
    questions: [
      { type: 'fill', question: 'She said, "___ I will come tomorrow."', correctAnswer: '"' },
      { type: 'mcq', question: '"It\'s" is a contraction of:', options: ['it is/it has','its own','it was','its self'], correctAnswer: 'it is/it has' },
      { type: 'error', question: 'Shes a good student.', correctAnswer: 'She\'s a good student.' },
      { type: 'fill', question: 'Ram___ book is on the table. (Add apostrophe)', correctAnswer: 'Ram\'s' },
      { type: 'mcq', question: 'Which punctuation separates items in a list?', options: ['full stop','comma','colon','semicolon'], correctAnswer: 'comma' },
      { type: 'error', question: 'She like tea coffee and juice.', correctAnswer: 'She likes tea, coffee, and juice.' },
      { type: 'transform', question: 'Rewrite with correct punctuation: "she asked where are you going"', correctAnswer: 'She asked, "Where are you going?"' },
      { type: 'error', question: 'Its raining outside.', correctAnswer: 'It\'s raining outside.' },
      { type: 'mcq', question: 'A semicolon (;) is used to:', options: ['end a sentence','join related independent clauses','start a list','show possession'], correctAnswer: 'join related independent clauses' },
      { type: 'fill', question: 'She is talented___ she is also hardworking. (Use semicolon)', correctAnswer: ';' },
    ]
  },
  {
    dayNumber: 36, topic: 'Idioms & Phrases', difficulty: 'hard', timeLimit: 1800,
    explanation: 'Idioms are phrases whose meanings differ from the literal meanings of individual words.',
    rules: ['Idioms cannot be translated literally', 'Learn them as fixed expressions', 'Context determines the correct idiom'],
    examples: ['"Bite the bullet" = endure a painful situation', '"Break the ice" = start a conversation', '"Hit the nail on the head" = exactly correct'],
    commonMistakes: ['Misusing idioms out of context', 'Changing words of fixed phrases'],
    questions: [
      { type: 'mcq', question: '"Break the ice" means:', options: ['break something made of ice','start a conversation','end a friendship','cause trouble'], correctAnswer: 'start a conversation' },
      { type: 'fill', question: '"Once in a blue ___" means rarely.', correctAnswer: 'moon' },
      { type: 'mcq', question: '"Bite the bullet" means:', options: ['eat something hard','endure a painful situation','hurt someone','bite someone'], correctAnswer: 'endure a painful situation' },
      { type: 'fill', question: '"Spill the ___" means to reveal a secret.', correctAnswer: 'beans' },
      { type: 'mcq', question: '"Hit the nail on the head" means:', options: ['hammer correctly','be exactly right','miss the point','make a mistake'], correctAnswer: 'be exactly right' },
      { type: 'fill', question: '"Under the ___" means feeling ill.', correctAnswer: 'weather' },
      { type: 'mcq', question: '"Let the cat out of the bag" means:', options: ['free an animal','reveal a secret accidentally','plan something','lose control'], correctAnswer: 'reveal a secret accidentally' },
      { type: 'fill', question: '"Burn the midnight ___" means to work late.', correctAnswer: 'oil' },
      { type: 'mcq', question: '"Cost an arm and a leg" means:', options: ['painful','very expensive','donate blood','physical injury'], correctAnswer: 'very expensive' },
      { type: 'fill', question: '"A blessing in ___" means a good thing that seemed bad at first.', correctAnswer: 'disguise' },
    ]
  },
  {
    dayNumber: 37, topic: 'One Word Substitution', difficulty: 'hard', timeLimit: 1800,
    explanation: 'One word substitution means using a single word to replace a phrase or group of words.',
    rules: ['Match the definition precisely', 'Context helps choose between similar words'],
    examples: ['"One who cannot read or write" = Illiterate', '"Fear of water" = Hydrophobia', '"Study of birds" = Ornithology'],
    commonMistakes: ['Confusing similar-sounding words', 'Choosing partially correct word'],
    questions: [
      { type: 'mcq', question: '"One who cannot read or write" is:', options: ['Literate','Illiterate','Introvert','Scholar'], correctAnswer: 'Illiterate' },
      { type: 'fill', question: '"Fear of water" is called ___.', correctAnswer: 'Hydrophobia' },
      { type: 'mcq', question: '"Study of birds" is:', options: ['Ornithology','Biology','Zoology','Botany'], correctAnswer: 'Ornithology' },
      { type: 'fill', question: '"A place where dead bodies are kept" is called a ___.', correctAnswer: 'Mortuary' },
      { type: 'mcq', question: '"One who travels to a holy place" is a:', options: ['Pilgrim','Nomad','Hermit','Vagabond'], correctAnswer: 'Pilgrim' },
      { type: 'fill', question: '"A doctor who treats children" is called a ___.', correctAnswer: 'Paediatrician' },
      { type: 'mcq', question: '"Words inscribed on a tomb" are called:', options: ['Epitaph','Epilogue','Obituary','Elegy'], correctAnswer: 'Epitaph' },
      { type: 'fill', question: '"Government by the people" is called ___.', correctAnswer: 'Democracy' },
      { type: 'mcq', question: '"One who hates mankind" is called:', options: ['Misogynist','Misanthrope','Philanthropist','Atheist'], correctAnswer: 'Misanthrope' },
      { type: 'fill', question: '"A person who is new to a field" is called a ___.', correctAnswer: 'Novice' },
    ]
  },
  {
    dayNumber: 38, topic: 'Synonyms & Antonyms', difficulty: 'medium', timeLimit: 1800,
    explanation: 'Synonyms are words with similar meanings. Antonyms are words with opposite meanings.',
    rules: ['Synonyms: same or similar meaning', 'Antonyms: opposite meaning', 'Context matters for synonym selection'],
    examples: ['Happy → Synonym: Joyful, Antonym: Sad', 'Brave → Synonym: Courageous, Antonym: Cowardly'],
    commonMistakes: ['Choosing a word that is close but not a synonym', 'Confusing synonym with antonym'],
    questions: [
      { type: 'mcq', question: 'Synonym of "Brave":', options: ['Cowardly','Courageous','Timid','Fearful'], correctAnswer: 'Courageous' },
      { type: 'fill', question: 'Antonym of "Ancient" is ___.', correctAnswer: 'Modern' },
      { type: 'mcq', question: 'Synonym of "Happy":', options: ['Sad','Angry','Joyful','Bored'], correctAnswer: 'Joyful' },
      { type: 'fill', question: 'Synonym of "Begin" is ___.', correctAnswer: 'Commence' },
      { type: 'mcq', question: 'Antonym of "Generous":', options: ['Kind','Miserly','Helpful','Giving'], correctAnswer: 'Miserly' },
      { type: 'fill', question: 'Antonym of "Victory" is ___.', correctAnswer: 'Defeat' },
      { type: 'mcq', question: 'Synonym of "Angry":', options: ['Calm','Furious','Happy','Bored'], correctAnswer: 'Furious' },
      { type: 'fill', question: 'Synonym of "Difficult" is ___.', correctAnswer: 'Arduous' },
      { type: 'mcq', question: 'Antonym of "Transparent":', options: ['Clear','Opaque','Bright','Light'], correctAnswer: 'Opaque' },
      { type: 'fill', question: 'Antonym of "Expand" is ___.', correctAnswer: 'Contract' },
    ]
  },
  {
    dayNumber: 39, topic: 'Comprehension – Reading & Analysis', difficulty: 'hard', timeLimit: 1800,
    explanation: 'Reading comprehension involves understanding, analyzing and interpreting a passage.',
    rules: ['Read the passage carefully before answering', 'Answers should be based on the passage', 'Use inference for implied meanings'],
    examples: ['Identify the main idea', 'Find the synonym of the given word in context', 'Answer in complete sentences'],
    commonMistakes: ['Answering from general knowledge instead of the passage', 'Missing implied meanings'],
    questions: [
      { type: 'fill', question: 'Passage: "The forest was silent. Not a leaf stirred." The mood of the passage is ___.', correctAnswer: 'calm/peaceful' },
      { type: 'mcq', question: '"She toiled day and night." "Toiled" means:', options: ['played','rested','worked hard','slept'], correctAnswer: 'worked hard' },
      { type: 'fill', question: 'The main idea of a passage is usually found in the ___ sentence.', correctAnswer: 'topic' },
      { type: 'mcq', question: 'A synonym for "enormous" from the options:', options: ['tiny','huge','empty','quiet'], correctAnswer: 'huge' },
      { type: 'fill', question: '"Despite the rain, she continued." The word "despite" shows ___.', correctAnswer: 'contrast' },
      { type: 'mcq', question: 'Inference means:', options: ['a direct quote','something stated clearly','a conclusion based on evidence','a definition'], correctAnswer: 'a conclusion based on evidence' },
      { type: 'fill', question: '"The children were thrilled." Antonym of "thrilled" is ___.', correctAnswer: 'disappointed' },
      { type: 'mcq', question: '"He burned the midnight oil." This is:', options: ['a simile','a metaphor','an idiom','a proverb'], correctAnswer: 'an idiom' },
      { type: 'fill', question: 'The title of a passage should reflect its ___ idea.', correctAnswer: 'main' },
      { type: 'mcq', question: '"She was as brave as a lion." This is a:', options: ['metaphor','idiom','simile','hyperbole'], correctAnswer: 'simile' },
    ]
  },
  {
    dayNumber: 40, topic: 'Grand Revision – Mixed Grammar', difficulty: 'hard', timeLimit: 1800,
    explanation: 'This final day covers all topics: tenses, voice, narration, sentence types, and more.',
    rules: ['Apply all grammar rules learned', 'Check tense, voice, agreement, punctuation', 'Read carefully before answering'],
    examples: ['Active/Passive, Direct/Indirect, Tenses, Conditionals, Articles, Prepositions'],
    commonMistakes: ['Rushing through questions', 'Mixing up rules from different topics'],
    questions: [
      { type: 'mcq', question: 'Change to passive: "She wrote a letter."', options: ['A letter is written by her.','A letter was written by her.','A letter has been written.','A letter will be written.'], correctAnswer: 'A letter was written by her.' },
      { type: 'fill', question: 'Indirect: He said, "I am tired." → He said that he ___ tired.', correctAnswer: 'was' },
      { type: 'mcq', question: '"If she had studied, she ___ passed." (Third Conditional)', options: ['would','will','would have','could'], correctAnswer: 'would have' },
      { type: 'error', question: 'She don\'t know the answer.', correctAnswer: 'She doesn\'t know the answer.' },
      { type: 'transform', question: '"He is the tallest boy." → Comparative', correctAnswer: 'He is taller than any other boy.' },
      { type: 'fill', question: '"What ___ brave girl she is!" (Use article)', correctAnswer: 'a' },
      { type: 'mcq', question: 'Which is in present perfect tense?', options: ['She goes.','She went.','She has gone.','She was going.'], correctAnswer: 'She has gone.' },
      { type: 'error', question: 'He have already finished his work.', correctAnswer: 'He has already finished his work.' },
      { type: 'fill', question: 'She works hard, ___ she? (Question tag)', correctAnswer: 'doesn\'t' },
      { type: 'mcq', question: '"Synonym of Courageous":', options: ['Fearful','Timid','Brave','Cowardly'], correctAnswer: 'Brave' },
    ]
  },
];

async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  await Lesson.deleteMany({});
  await Lesson.insertMany(lessons);
  console.log('Seeded', lessons.length, 'lessons');

  // Create admin user if not exists
  const adminExists = await Student.findOne({ email: 'admin@grammar40.com' });
  if (!adminExists) {
    await Student.create({
      name: 'Admin',
      rollNumber: 'ADMIN001',
      class: 'Admin',
      section: 'A',
      school: 'Grammar40',
      email: 'admin@grammar40.com',
      password: 'Admin@2025',
      role: 'admin',
      unlockedDays: Array.from({ length: 40 }, (_, i) => i + 1),
    });
    console.log('Admin user created: admin@grammar40.com / Admin@2025');
  }

  process.exit(0);
}

seed().catch(err => { console.error(err); process.exit(1); });
